config/routes.rb
Dropppin::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'home#index'

  post 'places' => 'places#create'
  post 'places/clear_all' => 'places#clear_all', as: :clear_all
  post 'places/clear_done' => 'places#clear_done', as: :clear_done
  put 'places/:id' => 'places#toggle_done'

end

app/models/place.rb
class Place < ActiveRecord::Base
  # before_create :default_values
  belongs_to :user

  private
    def default_values
      puts "default values woop!"
      puts self.done
      # self.name = "Thomas"
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2]

	has_many :places, dependent: :destroy
	validates :email, uniqueness: { case_sensitive: false }

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    unless user
        user = User.create(name: data["name"], email: data["email"],
            password: Devise.friendly_token[0,20])
    end
    user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @places = user_signed_in? ?
        current_user.places.where(cleared: false) : Place.none
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  respond_to :json

  def create
    @place = current_user.places
        .build(params[:place].permit(:name, :lat, :lng, :reference, :address))
    @place.done = false
    @place.cleared = false
    respond_to do |format|
      if @place.save!
        format.html { render :partial => "place", :locals => {:place => @place} }
      else
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  def toggle_done
    @place = current_user.places.find(params[:id])

    @place.done = !@place.done

    if @place.save!
      head :no_content
    else
      render status: :internal_server_error
    end
  end

  def clear_done
    @places = current_user.places.where(done: true).update_all(cleared: true)

    head :no_content
  end

  def clear_all
    @places = current_user.places.update_all(cleared: true)

    head :no_content
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
#todos
  %h1 Droppp.in
  - if user_signed_in?
    %div
      Signed in as
      = current_user.name
      %li= link_to('Logout', destroy_user_session_path, :method => 'delete')
  - else
    %li= link_to('Login', new_user_session_path)
    %li= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2)
  #settings
  .inner
    %input#place_name{:type => "text", :placeholder => "Add location"}
    %section
      = render "places/index"
    = link_to('Clear all', clear_all_path, :method => 'post', :id => 'clearLink')
    = link_to('Clear done', clear_done_path, :method => 'post', :id => 'clearDone')
    %em
      Search for places you'd like to go, add them to your list and we'll remember them next time you visit.

#map_canvas

%script{:type => "text/javascript", :src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyAhA2lQUp1m0vfXRCUXQcAJgKaiC99mwwQ&sensor=false&libraries=places"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Dropppin
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tag
  %body
    = yield

app/views/places/_index.html.haml
%ul#edit
  = render @places

app/views/places/_place.html.haml
%li.place{:class => ('done' if place.done?),
    :data => {:lat => place.lat, :lng => place.lng, :id => place.id}}
  %p.eventLocation= place.name
  %a.tickOff{:href => "/places/#{place.id}",
      :data => {:remote => 'true', :method => 'put'}}